### ISSUE TITLE
remove fmt.Println logging

### ISSUE THREAD

**Issue by arussellsaw** [statsig-io/go-sdk#27]
Hello! it looks like your most recent release added logging via fmt.Println, would it be possible to change that to either a configurable io.Writer, logger, or an option to disable logging altogether? at the moment our logs are intermingled with the statsig logs which makes consuming structured logging harder, and local dev is very noisy.

**Comment by edstell** [comment]
For context, [this](https://github.com/statsig-io/go-sdk/blob/33b71211d30dcfe83936f5df0cfd94c1f9a862a7/util.go#L40) is the log line which is particularly noisy

**Comment by kenny-statsig** [comment]
Yeah we can definitely do that! We'll make this configurable so you can customize how the log stream should be handled.

**Comment by kenny-statsig** [comment]
Added an option in v1.10.0 to plug in a custom logger as well as options to turn off logging for each process
