### ISSUE TITLE
Log message when there are no updates to specs

### ISSUE THREAD

**Issue by jakegavin** [statsig-io/go-sdk#28]
Currently, Statsig logs "Failed to process specs" when there are no updates to the specs [here](https://github.com/statsig-io/go-sdk/blob/33b71211d30dcfe83936f5df0cfd94c1f9a862a7/store.go#L312). "Failed" makes it sound like something has gone wrong but if I'm understanding this correctly, this is the most common scenario. As a result, we're seeing failure messages in our logs every 10 seconds. What do y'all think about changing the phrasing of this message to something along the lines of 

```
s.logProcess("Processing specs...")
if specs.HasUpdates {
    // process updates
} else {
  s.logProcess("No updates found")
}
s.logProcess("Done processing specs")
```

Am I misunderstanding something and this is `specs.HasUpdates` false is actually a bad state to be in?

**Comment by jkw-statsig** [comment]
This does seem weird, we will take a look

**Comment by kenny-statsig** [comment]
Updated the message to show "No updates to specs"
