### ISSUE TITLE
"Failed to initialize from the network." when running in LocalMode

### ISSUE THREAD

**Issue by Tadimsky** [statsig-io/go-sdk#30]
I have a functional test environment where I set `LocalMode = true` in the options.
However, the begging of my test output always shows 
> Failed to initialize from the network. See https://docs.statsig.com/messages/serverSDKConnection for more information

Can this be not emitted when in LocalMode?
There have been a lot of recent changes that have made the library way more verbose than before that we've noticed and we've had to make updates to the options to stop it from contaminating our logs in tests.
Is there a better way to do this?

**Comment by kenny-statsig** [comment]
Hey @Tadimsky this has been resolved in the latest version [v1.21.0](https://github.com/statsig-io/go-sdk/releases/tag/v1.21.0)
