### ISSUE TITLE
Roundtrip network call when using default key for local development.

### ISSUE THREAD

**Issue by jefftto** [statsig-io/go-sdk#6]
For local development, it would be nice to be able to use a secret key that will avoid a network call and use local default values instead. Currently, using a default secret key such as "secret-foo" will not panic but does make a round-trip network call.

**Comment by tore-statsig** [comment]
For visibility: this came from a discussion in the statsig slack channel.  It sounds like this is just the first in a broader set of asks for using the SDK slightly differently than in a go webserver scenario.  We will continue to update this issue as it is impacted and addressed, but there will be a more sweeping set of changes to unblock your use case.

**Comment by tore-statsig** [comment]
Added `localMode` in https://github.com/statsig-io/go-sdk/releases/tag/v1.1.0
